name: flex_color_scheme_example
description: Examples that demonstrate how to use the FlexColorScheme package.
version: 4.0.0
publish_to: 'none'
environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

  # Color scheme package (by Mike Rydstrom, rydmike.com).
  flex_color_scheme:
    path: ../

  # The Flutter SDK (by Google flutter.dev).
  flutter:
    sdk: flutter

  # Used for all masonry grid layout (by Romain Rastel).
  flutter_staggered_grid_view: ^0.4.1

  # Google fonts (by Google material.io).
  google_fonts: ^2.1.0

  # Hive local storage (by Simon Leir).
  hive: ^2.0.4

  # Store value pair shared preference data (by Google flutter.dev).
  shared_preferences: ^2.0.8

  # Used for launching a WEB URL (by Google flutter.dev).
  url_launcher: ^6.0.12

  # Masonry layout like staggered grid (by fluttercandies.com).
  # Compare this one to Staggered Grid and decide which one to use.
  waterfall_flow: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
