name: flex_color_scheme_example
description: Examples that demonstrate how to use the FlexColorScheme package.
version: 4.0.0
publish_to: 'none'
environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

  # Color scheme package, by Mike Rydstrom, rydmike.com, @rydmike.
  flex_color_scheme:
    path: ../

  # The Flutter SDK, by Google flutter.dev.
  flutter:
    sdk: flutter

  # Masonry grid layout, by Romain Rastel.
  #
  # Went with waterfall_flow instead of flutter_staggered_grid_view for this
  # example 5. However, both packages have similar issue.
  #
  flutter_staggered_grid_view: ^0.4.1

  # Google fonts, by Google material.io.
  google_fonts: ^2.1.0

  # Hive local storage, by Simon Leir.
  hive: ^2.0.4

  # The Material Design Icons designed
  material_design_icons_flutter: ^5.0.6295

  # Store value pair shared preference data, by Google flutter.dev.
  # Needed some better platform icons for example 5 app.
  # https://materialdesignicons.com/
  shared_preferences: ^2.0.8

  # Used for launching a WEB URL, by Google flutter.dev.
  url_launcher: ^6.0.12

  # Masonry layout like staggered grid, by fluttercandies.com.
  #
  # Compared this one with Staggered Grid and decided to use this one in this
  # case. It felt a bit faster, but both are equally bad when it comes
  # handling varying amount of columns and changes in it due to calculation
  # of columns to used based on change in media size and resulting layout area.
  # Might be a shared underlying issues in the SDK that is causing the problem.
  waterfall_flow: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
