name: flex_color_scheme
description: A Flutter package to use and make beautiful Material design based themes.
version: 5.0.0-dev.1
homepage: https://github.com/rydmike/flex_color_scheme
environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
