name: flex_color_scheme
description: A Flutter package to use and make beautiful Material design based themes.
version: 7.0.0-dev.3
homepage: https://docs.flexcolorscheme.com
repository: https://github.com/rydmike/flex_color_scheme
issue_tracker: https://github.com/rydmike/flex_color_scheme/issues
documentation: https://docs.flexcolorscheme.com
screenshots:
  - description: 'Example of FlexColorScheme light theme colors in Themes Playground theme simulator'
    path: example/screenshots/fcs_colors_light.png
  - description: 'Example of FlexColorScheme dark theme colors in Themes Playground theme simulator'
    path: example/screenshots/fcs_colors_dark.png
  - description: 'FlexColorScheme light theme applied to a mock login screen in Themes Playground'
    path: example/screenshots/fcs_login_light.png
  - description: 'FlexColorScheme dark theme applied to a mock login screen in Themes Playground'
    path: example/screenshots/fcs_login_dark.png
  - description: 'FlexColorScheme light theme applied to a mock shop app in Themes Playground'
    path: example/screenshots/fcs_shop_light.png
  - description: 'FlexColorScheme dark theme applied to a mock shop app in Themes Playground'
    path: example/screenshots/fcs_shop_dark.png
  - description: 'A FlexColorScheme pink light theme applied on the Flutter M3 demo app in Themes Playground'
    path: example/screenshots/fcs_pad_light.png
  - description: 'A FlexColorScheme pink dark theme applied on the Flutter M3 demo app in Themes Playground'
    path: example/screenshots/fcs_pad_dark.png
  - description: 'A FlexColorScheme blue light theme applied on the Flutter M3 demo app in Themes Playground'
    path: example/screenshots/fcs_big_pad_light.png
  - description: 'A FlexColorScheme blue dark theme applied on the Flutter M3 demo app in Themes Playground'
    path: example/screenshots/fcs_big_pad_dark.png

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  # FlexSeedScheme package, by Mike Rydstrom, rydmike.com (@rydmike).
  # https://pub.dev/packages/flex_seed_scheme
  flex_seed_scheme: ^1.2.0

  flutter:
    sdk: flutter

  # Annotations used to express developer intentions that can't otherwise be deduced by
  # statically analyzing source code. Package is from Google dart.dev team.
  #
  # Flutter does not expose the "@internal" annotation via foundation, to use it we need to
  # import the package.
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Color utilities by Google (material.io).
  #
  # Used to compute and create Tonal Palette theme colors.
  #
  # Flutter SDK from 2.10.0 stable also uses and depends on this package.
  # Version 0.3.0 contains many new features, but Flutter stable and master are
  # locked to version 0.2.0, so we cannot use it, also 0-ver does not
  # upgrade from version ^0.2.0 to 0.3.x, only to 0.2.x.
  material_color_utilities: ^0.2.0

  test:
