name: flex_color_scheme
description: A Flutter package to use and make beautiful Material design based themes.
version: 7.0.0-dev.2
homepage: https://docs.flexcolorscheme.com
repository: https://github.com/rydmike/flex_color_scheme
issue_tracker: https://github.com/rydmike/flex_color_scheme/issues
documentation: https://docs.flexcolorscheme.com
environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.7.0'

dependencies:
  # FlexSeedScheme package, by Mike Rydstrom, rydmike.com (@rydmike).
  # https://pub.dev/packages/flex_seed_scheme
  flex_seed_scheme: ^1.2.0

  flutter:
    sdk: flutter

  # Annotations used to express developer intentions that can't otherwise be deduced by
  # statically analyzing source code. Package is from Google dart.dev team.
  #
  # Flutter does not expose the "@internal" annotation via foundation, to use it we need to
  # import the package.
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Color utilities by Google (material.io).
  #
  # Used to compute and create Tonal Palette theme colors.
  # Flutter SDK from 2.10.0 stable also uses and depends on this package.
  material_color_utilities: ^0.2.0

  test:
